todoproj/todoapp/urls.py
from django.urls import path
from .import views

app_name = 'todoapp'

urlpatterns = [
    path('', views.home, name='home'),
    path('delete/<int:id>/', views.delete, name='delete'),
    path('update/<int:id>/', views.update, name='update'),
    path('cbvhome/', views.TaskListview.as_view(), name='cbvhome'),
    path('cbvdetail/<int:pk>/',views.taskdetailview.as_view(),name='cbvdetail'),
    path('cbvupdate/<int:pk>/',views.Taskupdateview.as_view(), name='cbvupdate'),
    path('cbvdelete/<int:pk>/',views.Taskdeleteview.as_view(),name='cbvdelete'),
]

todoproj/todoproj/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('todoapp.urls')),
]

todoproj/todoapp/models.py
from django.db import models

# Create your models here.
class Task(models.Model):

    name=models.CharField(max_length=250)
    priority=models.IntegerField(blank=True, default=0)
    date=models.DateField()

    def __str__(self):
        return self.name

todoproj/todoapp/forms.py
from django import forms
from .models import Task

class TodoForm(forms.ModelForm):
    class Meta:
        model=Task
        fields=['name','priority','date']

todoproj/todoapp/views.py
from django.shortcuts import render, redirect
from django.urls import reverse_lazy

from .models import Task


# Create your views here.
from .forms import TodoForm
from django.views.generic import ListView
from django.views.generic.detail import DetailView
from django.views.generic import UpdateView
from django.views.generic import DeleteView




class TaskListview(ListView):
    model=Task
    template_name = "home.html"
    context_object_name = 'task1'

class taskdetailview(DetailView):
    model=Task
    template_name = 'detail.html'
    context_object_name = 'task'

class Taskupdateview(UpdateView):
    model=Task
    template_name='update.html'
    context_object_name='task'
    fields=('name','priority','date')


def get_success_url(self):
    return reverse_lazy('cbvdetail',kwargs={'pk':self.object.id})

class Taskdeleteview(DeleteView):
    model=Task
    template_name = 'delete.html'
    success_url = reverse_lazy('cbvhome')

def home(request):
    task1 = Task.objects.all()
    if request.method =='POST':
            name = request.POST.get('task','' )
            priority = request.POST.get('priority','' )
            date=request.POST.get('date','')
            task= Task(name=name, priority=priority, date=date)
            task.save()

    return render(request,"home.html",{'task':task1})


def delete(request,id):
    if request.method=='POST':
        task=Task.objects.get(id=id)
        task.delete()
        return redirect('/')
    return render(request,'delete.html')

def update(request,id):
    task=Task.objects.get(id=id)
    form=TodoForm(request.POST or None, request.FILES, instance=task)
    if form.is_valid():
        form.save()
        return redirect('/')
    return render(request,'edit.html',{'form':form,'task':task})

todoproj/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/css/bootstrap.min.css" integrity="sha384-zCbKRCUGaJDkqS1kPbPd7TveP5iyJE0EjAuZQTgFLD2ylzuqKfdKlfG/eSrtxUkn" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'style.css' %}">
</head>
<body>
{% block content %}
{% endblock %}
</body>
</html>

todoproj/templates/delete.html
{% extends 'base.html' %}

{% block content %}

<form method="POST">
    {% csrf_token %}
    <p>Are u sure this task is done??</p>
    <button type="submit">Confirm</button>
</form>
{% endblock %}

todoproj/templates/detail.html
{% extends 'base.html' %}

{% block content %}
<div class="card shadow p-3 mb-5 bg-body rounded">
                <div class="card-body">
                    <h5 class="card-title">Task Name: {{task.name}}</h5>
                    <p><b>Priority : {{task.priority}}</b></p>
                    <p><b>Date: {{task.date}}</b></p>
                    <a class="btn btn-danger" href="{% url 'todoapp:delete' task.id %}">Done</a>
                    <a class="btn btn-success" href="{% url 'todoapp:update' task.id %}">Update</a>

                </div>
</div>
{% endblock %}

todoproj/templates/edit.html
{% extends 'base.html' %}

{% block content %}

<form method="POST">
    {% csrf_token %}
    {{form.as_p}}
    <button type="submit">Update</button>
</form>
{% endblock %}

todoproj/templates/home.html
{% extends 'base.html' %}
{% block content %}
<div class="container-fluid">
    <div class="row">
        <div class="col-md-12">
            <div class="banner" style="background-color:#DEB887; width:100%; height:200px; margin-bottom:50px;">
                <div class="banner-text" style="top:50%; left:40%; position:absolute; transform:transform;">
                    <h1>ToDo List</h1>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="container">
    <div class="row ">
        <div class="col-md-6">
            <form method="POST" class="shadow-lg p-3 mb-5 bg-white rounded">
                {% csrf_token %}
                <div class="form-group">
                    <label for="task">Task : </label>
<!--            <div class="col-sm-10">-->
                    <input type="text" class="form-control"   name="task">
<!--            </div>-->
                </div>
                <div class="form-group">
                    <label for="priority">Priority : </label>
                    <input type="text" class="form-control" name ="priority">
                </div>

                <div class="form-group">
                    <label for="date">Date : </label>
                    <input type="date" class="form-control" name ="date">
                </div>
                    <input type="submit" class="btn btn-success">

            </form>



        </div>
        <div class="col-md-6">
            {% for i in task %}
            <div class="card shadow p-3 mb-5 bg-body rounded">
                <div class="card-body">
                    <h5 class="card-title">Task Name: {{i.name}}</h5>
                    <p><b>Priority : {{i.priority}}</b></p>
                    <p><b>Date: {{i.date}}</b></p>
                    <a class="btn btn-danger" href="{% url 'todoapp:delete' i.id %}">Done</a>
                    <a class="btn btn-success" href="{% url 'todoapp:update' i.id %}">Update</a>

                </div>
            </div>

            {% endfor %}

        </div>
    </div>
 </div>
{% endblock %}

todoproj/templates/update.html
{% extends 'base.html' %}

{% block content %}
<div class="card">
    <div class="card-header">
        <div class="card-title">
            Task Updated
        </div>
        <div class="card-body">
            <form method="POST">
                {% csrf_token %}
                {{form.as_p}}
                <button type="submit">Update</button>
            </form>
        </div>
    </div>
</div>

{% endblock %}